In [14]:
import pandas as pd

# Cargando archivo CSV original
df_ipc = pd.read_csv('./data/IPCCUADROS.csv' , encoding='ANSI')

# Actualizar códigos de nivel por descripciones de nivel
# D = DIVISION
# G = GRUPO
# C = CLASE
# S = SUBCLASE
# P = PRODUCTO
df_ipc['IPCCUANIVEL'] = df_ipc['IPCCUANIVEL'].replace({'D': 'DIVISION'})
df_ipc['IPCCUANIVEL'] = df_ipc['IPCCUANIVEL'].replace({'G': 'GRUPO'})
df_ipc['IPCCUANIVEL'] = df_ipc['IPCCUANIVEL'].replace({'C': 'CLASE'})
df_ipc['IPCCUANIVEL'] = df_ipc['IPCCUANIVEL'].replace({'S': 'SUBLCASE'})
df_ipc['IPCCUANIVEL'] = df_ipc['IPCCUANIVEL'].replace({'P': 'PRODUCTO'})

# Sustituir códigos de región por descripciones de regiones
# 1 = MONTEVIDEO
# 2 = INTERIOR
# 3 = PAIS
df_ipc['IPCCUAREGION'] = df_ipc['IPCCUAREGION'].replace({1: 'MONTEVIDEO'})
df_ipc['IPCCUAREGION'] = df_ipc['IPCCUAREGION'].replace({2: 'INTERIOR'})
df_ipc['IPCCUAREGION'] = df_ipc['IPCCUAREGION'].replace({3: 'TOTAL_PAIS'})


# Eliminar columnas 
df_ipc = df_ipc.drop(columns=['IPCCUASEMANA'])
df_ipc = df_ipc.drop(columns=['IPCCUAINDPONDERACION'])
df_ipc = df_ipc.drop(columns=['IPCCUAINDICE'])
df_ipc = df_ipc.drop(columns=['IPCCUAINCMENSUAL'])
df_ipc = df_ipc.drop(columns=['IPCCUAINCANUAL'])
df_ipc = df_ipc.drop(columns=['IPCCUAINCACUMANUAL'])
df_ipc = df_ipc.drop(columns=['IPCCUAVARACUMANUAL'])

# Eliminar los registros de nivel Y
df_ipc = df_ipc[df_ipc['IPCCUANIVEL'] != 'Y']

# Actualizar Nombres de Columnas
df_ipc.rename(columns={'IPCCUAANIO': 'ANIO'}, inplace=True)
df_ipc.rename(columns={'IPCCUAMES': 'MES'}, inplace=True)
df_ipc.rename(columns={'IPCCUAREGION': 'REGION'}, inplace=True)
df_ipc.rename(columns={'IPCCUANIVEL': 'NIVEL'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDDIVISION': 'DIVISION'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDGRUPO': 'GRUPO'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDCLASE': 'CLASE'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDSUBCLASE': 'SUBCLASE'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDPRODUCTO': 'PRODUCTO'}, inplace=True)
df_ipc.rename(columns={'IPCCUAINDDESCRIPCION': 'DESCRIPCION'}, inplace=True)
df_ipc.rename(columns={'IPCCUAVARMENSUAL': 'VAR_MENSUAL'}, inplace=True)
df_ipc.rename(columns={'IPCCUAVARANUAL': 'VAR_ANUAL'}, inplace=True)

# Crear un nuevo CSV con la data transformada que será el origen de datos del dashboard 
df_ipc.to_csv('./data/IPCDATA.csv', index=False)

df_ipc

,ANIO,MES,REGION,NIVEL,DIVISION,GRUPO,CLASE,SUBCLASE,PRODUCTO,DESCRIPCION,VAR_MENSUAL,VAR_ANUAL
0,2022,11,MONTEVIDEO,CLASE,5,053,0531,,,Grandes electrodomésticos,-1.700771,0.0
1,2022,11,INTERIOR,CLASE,5,053,0531,,,Grandes electrodomésticos,-2.769848,0.0
2,2022,11,TOTAL_PAIS,CLASE,5,053,0531,,,Grandes electrodomésticos,-2.267929,0.0
3,2022,11,MONTEVIDEO,PRODUCTO,5,053,0531,05311,05311002,Cocinas,0.434115,0.0
4,2022,11,INTERIOR,PRODUCTO,5,053,0531,05311,05311002,Cocinas,-1.898935,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
48161,2024,10,INTERIOR,PRODUCTO,13,131,1312,13120,13120009,Pañales desechables,0.000000,0.0
48162,2024,10,TOTAL_PAIS,PRODUCTO,13,131,1312,13120,13120009,Pañales desechables,0.000000,0.0
48163,2024,10,MONTEVIDEO,PRODUCTO,13,131,1312,13120,13120010,Cosméticos y perfumes,0.000000,0.0
48164,2024,10,INTERIOR,PRODUCTO,13,131,1312,13120,13120010,Cosméticos y perfumes,0.000000,0.0
48165,2024,10,TOTAL_PAIS,PRODUCTO,13,131,1312,13120,13120010,Cosméticos y perfumes,0.000000,0.0